### ISSUE TITLE
Ajax filter does not account for Woocommerce ajax calls

### ISSUE THREAD

**Issue by 1000camels** [kagg-design/disable-plugins#1]
This plugin looks great.
Unfortunately, it does not support Woocommerce Ajax calls which do not use admin-ajax.php and ?action, but instead use ?wc-ajax=.

I am trying to evolve your code to support this pattern, but if you have any advice, it would be appreciated.

**Comment by kagg-design** [comment]
Thank you.

I will add this feature on weekend.

**Comment by 1000camels** [comment]
Wonderful.

I hacked together something that worked, but i suspect your version will be better.

A few notes for you. Woocommerce Ajax calls are not recognized by wp_doing_ajax (not sure why).
I resolved this with this in your plugin:

add_filter( 'wp_doing_ajax', function( $is_doing_ajax ) {
    if( isset($_REQUEST['wc-ajax']) ) {
        return true;
    }
},1);

I've also been doing a lot of research on performance issues with ajax and many people are saying that wc-ajax style calls are lighter than admin-ajax.php, which might explain the shift. Although I do not know yet why it is happening. But your plugin is amazing and will likely solve some series issues I have been having.

One other thing I noticed. Your 'enabled_plugins' did not do what I thought it would. It is not a whitelist, but rather a way to add unactivated plugins. Pretty neat, but wondering whether it would be nice to have a setting to say just load this group of plugins, bypassing both disabled_plugins and enabled_plugins. The reason I am using your plugin is that I have a few calls which really only need woocommerce. I would love to be able to just specify a few plugins.

**Comment by 1000camels** [comment]
The only other thing I stumbled on was syntax errors in my json, which perhaps could be caught earlier and send a message to error_log.

**Comment by kagg-design** [comment]
The filter you proposed works, allowing the plugin to check filters for the action. But because there is no `$_POST['action']` in wc-ajax request, the plugin does nothing.

I have added the relevant code and tests to the plugin, so now under tag 1.3 it can filter wc-ajax. Use location `ajax` for it.
